# Site settings
title: I'm A Barista, But I Don't Understand Java Jokes
email: enorton10@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Now, the story of a young woman who is learning to code and the one time she had no choice but to open 50 tabs in one browser.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: enorton10
github_username:  enorton10

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"